name: donorconnect
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  
  flutter_image_slideshow: ^0.1.6 
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_auth_web: ^5.8.14

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.png
  - assets/images/hospital.jpg
  - assets/images/blood_donation.jpg 
  - assets/images/blood_donation.jpg
  - assets/images/donor_2.jpg
  - assets/images/blood_drive.jpg
  - assets/images/donation1.jpeg
  - assets/images/donation2.jpeg
  - assets/images/donation3.jpeg
  - assets/images/qr_code.jpeg
  - assets/images/roti_bank.jpeg

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
